knowledge_base = {
    "python": "Python is a high-level, interpreted programming language known for its readability and flexibility. It is widely used for web development, data analysis, AI, and more.",
    "machine learning": "Machine Learning is a branch of artificial intelligence where machines learn from data and improve their performance without being explicitly programmed.",
    "blockchain": "Blockchain is a distributed ledger technology that allows data to be securely stored across a decentralized network. It is most famous for its use in cryptocurrencies like Bitcoin.",
    "html": "HTML (Hypertext Markup Language) is the standard language used to create web pages. It structures content on the web and is often paired with CSS and JavaScript for styling and functionality.",
    "Physics": "Physics is the fundamental science that studies matter, energy, and their interactions. It seeks to understand the basic principles governing the natural world, from the smallest subatomic particles to the vast expanses of the universe. Key areas of study in physics include mechanics, thermodynamics, electromagnetism, and quantum mechanics.",
    "Biology" : "Biology is the science of life, exploring the structure, function, growth, evolution, and distribution of living organisms. It encompasses a wide range of subdisciplines, including molecular biology, genetics, ecology, and evolutionary biology. Biologists study everything from the inner workings of cells to the complex interactions within ecosystems.",
    "Chemistry": """Chemistry is the study of matter, its properties, and how it interacts with energy. It investigates the composition, structure, and transformation of substances at the atomic and molecular level. Chemistry plays a crucial role in understanding the world around us and has applications in fields such as medicine, materials science, and environmental studies. These three branches of science are deeply interconnected, often overlapping in areas such as biochemistry, biophysics, and physical chemistry. Together, they provide a comprehensive framework for understanding the natural world and drive innovations that shape our modern society.""",
    "How can we see": "We see with the aid of our eyes but is only eyes important",
    "Luminous objects" : "Luminous objects are objects that emit their Light",
    "Non Luminous objects" : "Non-luminous objects that do not emit their Light but depend on another luminous object",
    "Classification":"Grouping animals into different levels based on their common characteristics is known as classification",
    "Displacement":"Describes how far an object moves from its initial position. It includes both magnitude and direction.",
    "Final Velocity":"The speed of an object at the end of a time interval, factoring in initial velocity and acceleration.",
    "Velocity":"The rate at which an object changes its position, a vector quantity with both speed and direction.",
    "Acceleration":"The rate at which an object’s velocity changes over time.",
    "Newton’s 2nd Law of Motion":"The force needed to accelerate an object is proportional to its mass and acceleration.",
    "Force":"A push or pull on an object that causes it to accelerate.",
    "Weight":"The force of gravity acting on an object’s mass.",
    "Momentum":"The product of an object's mass and velocity, representing how much motion it has.",
    "Impulse":"The change in momentum of an object when a force is applied over time.",
    "Work":"The energy transferred when a force moves an object over a distance.",
    "Kinetic Energy":"The energy an object possesses due to its motion.",
    "Potential Energy":"The energy stored in an object due to its position (like height in a gravitational field).",
    "Mechanical Energy":"The total energy (kinetic + potential) an object has.",
    "Power":"The rate at which work is done or energy is transferred.",
    "Gravitational Force":"The attractive force between two masses.",
    "Acceleration due to Gravity":"The rate of acceleration for an object in free fall near Earth’s surface.",
    "Centripetal Force ":"A push or pull on an object that causes it to accelerate.",
    "Angular Velocity":"The rate at which an object rotates around a point or axis.",
    "Tangential Velocity ":"The speed of an object moving along a circular path at a particular radius.",
    "Displacement":"The distance of an oscillating object from its equilibrium position.",
    "Period":"The time taken for one complete oscillation or cycle.",
    "Potential Energy ":"Energy stored in the system at maximum displacement in simple harmonic motion.",
    "First Law of Thermodynamics":"Energy in a system is conserved; it can change forms but not be created or destroyed.",
    "Ideal Gas Law":"Describes the behavior of an ideal gas in terms of pressure, volume, and temperature.",
    "Heat":"Describes the behavior of an ideal gas in terms of pressure, volume, and temperature.",
    "Work Done by a Gas":"The work performed by a gas when it expands or compresses.",
    "Coulomb’s Law":"Describes the electric force between two charged objects.",
    "Electric Field":"The force per unit charge exerted by a charged object.",
    "Electric Potential Energy":"The energy a charge has due to its position in an electric field.",
    "Capacitance":"The ability of a system to store electric charge per unit voltage.",
    "Ohm’s Law":"The relationship between voltage, current, and resistance in an electrical circuit.",
    "Power": "The rate at which electrical energy is used or generated.",
    "Wave Speed":"The speed at which a wave propagates through a medium.",
    "Frequency":"The number of complete wave cycles that pass a point in a given time period.",
    "Doppler Effect ":"The change in frequency or wavelength of a wave as observed by someone moving relative to the wave source.",
    "Snell's Law":"Describes how light bends when passing between two materials with different refractive indices.",
    "Lens Formula":"Relates the focal length of a lens to the object distance and the image distance.",
    "Magnification":"The ratio of the image height to the object height, describing how much an image is enlarged.",
    "Force Magnification":"The ratio of the image height to the object height, describing how much an image is enlarged.",
    "Einstein’s Mass-Energy Relation":"Describes how mass can be converted into energy and vice versa.",
    "Photoelectric Effect":"The emission of electrons from a material when it absorbs light energy.",
    "De Broglie Wavelength":"The wavelength associated with a particle due to its momentum, central to quantum mechanics."
}